### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by wangzhedaye** [SXU-CICI/bilstm_mpoa#1]
你们用的这个数据集是什么格式的，可以在上面提供一下吗，谢谢啦

**Comment by JiyaoWei** [comment]
这就是评测数据呀，这是评测网址https://www.biendata.com/competition/smpecisa2019/


 
---原始邮件---
发件人: "wangzhedaye"<notifications@github.com&gt;
发送时间: 2019年9月19日(星期四) 下午3:56
收件人: "SXU-CICI/bilstm_mpoa"<bilstm_mpoa@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [SXU-CICI/bilstm_mpoa] 数据集 (#1)



你们用的这个数据集是什么格式的，可以在上面提供一下吗，谢谢啦

**Comment by qimg412** [comment]
你好，数据集好像要参赛才能获取

**Comment by chengfanCF** [comment]
你好，请问实验用到的数据集有吗，可以提供一下吗，谢谢

**Comment by JiyaoWei** [comment]
新评测平台网址为http://sa-nsfc.com/evaluation/，数据集可以在该平台下载

**Comment by JiyaoWei** [comment]
数据集可以在新评测平台下载，平台网址为http://sa-nsfc.com/evaluation/

**Comment by qimg412** [comment]
嗯，感谢你的解答，已经获得数据集

从 Windows 版邮件发送

发件人: Jiyao
发送时间: 2021年10月8日 16:03
收件人: JiyaoWei/bilstm_mpoa
抄送: qimg412; Comment
主题: Re: [JiyaoWei/bilstm_mpoa] 数据集 (#1)

Closed #1.
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
